### ISSUE TITLE
A opção para download ainda funciona?

### ISSUE THREAD

**Issue by hirios** [cleitonleonel/Scripts_Python#1]
Tentei utilizar aqui e não tive sucesso. Segue aqui o meu sistema e a saída do erro ao tentar baixar:

LSB Version:	n/a
Distributor ID: ManjaroLinux
Description: Manjaro Linux
Release:	18.0.4
Codename: Illyria

`Traceback (most recent call last):
  File "rede.py", line 291, in <module>
    video_url = rede.get_stream(url=player_url['player'], referer=player_url['embed'])
  File "rede.py", line 151, in get_stream
    html = self.open(url, referer)
  File "rede.py", line 53, in open
    self.request = s.get(url, headers=headers)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/player3/serverf3playerfree.php?vid=DRESTNHO': No schema supplied. Perhaps you meant http:///player3/serverf3playerfree.php?vid=DRESTNHO?
`

**Comment by cleitonleonel** [comment]
Opa,ok!!! vou dar uma revisada nessa parte,mas os outros menus
funcionaram???

Em ter, 24 de set de 2019 às 10:38, Alan Rios <notifications@github.com>
escreveu:

**Comment by hirios** [comment]
Sim, as outras funções estão ok! Eu alterei algumas linhas a partir da linha 288 e agora o download funciona:

> player_url = rede.get_player('https://redecanais.rocks/aladdin-dublado-2019-1080p_0a5f56799.html')
player = f"https://cometa.top{player_url['player']}"
embed = f"https://cometa.top{player_url['embed']}"
print()
video_url = rede.get_stream(url=player, referer=embed)
rede.download(video_url)

**Comment by cleitonleonel** [comment]
Ah,sim...eu havia acertado isso,mas não fiz commit,foi só um erro na hora
de montar o link...falta de atenção minha...de todo  modo brigado por dar o
feedback.

Em ter, 24 de set de 2019 às 22:00, Alan Rios <notifications@github.com>
escreveu:

**Comment by cleitonleonel** [comment]
Esse site é muito bom,porém muda  muito os links do player,aí preciso mesmo
do feedback para ir acertando...mas na maioria das vezes é coisa simples...


Em ter, 24 de set de 2019 às 22:43, Cleiton Leonel Creton <
cleiton.leonel@gmail.com> escreveu:

**Comment by hirios** [comment]
Realmente o site é bem bacana e o projeto também é bem massa. No momento tu não tem interesse em um projeto similar, porém, com torrent? Te marquei no grupo do facebook uma vez, não sei se chegou a ver

**Comment by cleitonleonel** [comment]
Vc diz aquele de criar um player pra rodar filmes Torrent enquanto baixa???

Em qua, 25 de set de 2019 10:16, Alan Rios <notifications@github.com>
escreveu:

**Comment by hirios** [comment]
Sim!! Tem uma ferramenta feita em JS chamada peerflix, não sei se conhece, que funciona bem! Qual s.o tu usa? 
O peerflix é muito fácil de usar, você tendo o vlc instalado é só fazer que vai rodar:
peerflix link_magnético --vlc

Do contrário, pode usar somente para fazer os downloads mesmo

**Comment by cleitonleonel** [comment]
Linux,conheço não...perflix...

Em qua, 25 de set de 2019 11:30, Alan Rios <notifications@github.com>
escreveu:

**Comment by hirios** [comment]
https://github.com/hirios/partuf/
Dê uma olhada depois! A versão pra windows está desatualizada... hasdafas

**Comment by cleitonleonel** [comment]
Valeu...

Em qua, 25 de set de 2019 11:40, Alan Rios <notifications@github.com>
escreveu:
